# Generated by Django 5.2.5 on 2025-08-31 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inwestycja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("adres", models.CharField(max_length=255)),
                (
                    "zdjecie",
                    models.ImageField(blank=True, null=True, upload_to="inwestycje/"),
                ),
                ("data_dodania", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adres", models.CharField(max_length=255)),
                (
                    "metraz",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("pokoje", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dostepne", "Dostępne"),
                            ("sprzedane", "Sprzedane"),
                            ("rezerwacja", "Rezerwacja"),
                        ],
                        default="dostepne",
                        max_length=20,
                    ),
                ),
                (
                    "ostatnia_cena",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("data_dodania", models.DateTimeField(auto_now_add=True)),
                (
                    "inwestycja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oferty",
                        to="oferty.inwestycja",
                    ),
                ),
            ],
        ),
    ]
