# Generated by Django 5.2.5 on 2025-08-31 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inwestycja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("opis", models.TextField(blank=True)),
                ("zdjecie", models.ImageField(blank=True, upload_to="inwestycje/")),
                (
                    "data_dodania",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Inwestycja",
                "verbose_name_plural": "Inwestycje",
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adres", models.CharField(max_length=255)),
                (
                    "metraz",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cena",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dostepne", "Dostępne"),
                            ("rezerwacja", "Rezerwacja"),
                            ("sprzedane", "Sprzedane"),
                        ],
                        default="dostepne",
                        max_length=20,
                    ),
                ),
                ("pokoje", models.IntegerField(blank=True, null=True)),
                (
                    "zdjecie",
                    models.ImageField(blank=True, null=True, upload_to="oferty/"),
                ),
                (
                    "data_dodania",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "inwestycja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oferty",
                        to="oferty.inwestycja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Oferty",
            },
        ),
    ]
