# Generated by Django 5.2.5 on 2025-08-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adres", models.CharField(max_length=255)),
                ("metraz", models.CharField(max_length=50)),
                ("pokoje", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dostępne", "Dostępne"),
                            ("sprzedane", "Sprzedane"),
                            ("rezerwacja", "Rezerwacja"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kwota", models.CharField(max_length=50)),
                ("data", models.DateField()),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ceny",
                        to="oferty.oferta",
                    ),
                ),
            ],
        ),
    ]
