# Generated by Django 5.2.5 on 2025-09-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oferta",
            name="inwestycja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oferty",
                to="oferty.inwestycja",
            ),
        ),
    ]
