# Generated by Django 5.2.5 on 2025-08-28 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cena",
            options={"ordering": ["data"]},
        ),
        migrations.AddField(
            model_name="oferta",
            name="data_dodania",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="oferta",
            name="metraz",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("Dostępne", "Dostępne"),
                    ("Sprzedane", "Sprzedane"),
                    ("Rezerwacja", "Rezerwacja"),
                ],
                default="Dostępne",
                max_length=50,
            ),
        ),
    ]
