# Generated by Django 5.2.5 on 2025-08-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oferta",
            name="inwestycja",
        ),
        migrations.RemoveField(
            model_name="oferta",
            name="ostatnia_cena",
        ),
        migrations.AddField(
            model_name="oferta",
            name="zdjecie",
            field=models.ImageField(blank=True, null=True, upload_to="inwestycje/"),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="metraz",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="pokoje",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("dostępne", "Dostępne"),
                    ("sprzedane", "Sprzedane"),
                    ("rezerwacja", "Rezerwacja"),
                ],
                default="dostępne",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Cena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data", models.DateField()),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ceny",
                        to="oferty.oferta",
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
            },
        ),
        migrations.DeleteModel(
            name="Inwestycja",
        ),
    ]
