# Generated by Django 5.2.5 on 2025-08-31 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inwestycja",
            options={},
        ),
        migrations.AlterModelOptions(
            name="oferta",
            options={},
        ),
        migrations.RenameField(
            model_name="oferta",
            old_name="cena",
            new_name="ostatnia_cena",
        ),
        migrations.RemoveField(
            model_name="inwestycja",
            name="opis",
        ),
        migrations.RemoveField(
            model_name="oferta",
            name="zdjecie",
        ),
        migrations.AddField(
            model_name="inwestycja",
            name="adres",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inwestycja",
            name="data_dodania",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="inwestycja",
            name="nazwa",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inwestycja",
            name="zdjecie",
            field=models.ImageField(blank=True, null=True, upload_to="inwestycje/"),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="data_dodania",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="metraz",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="pokoje",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("dostepne", "Dostępne"),
                    ("sprzedane", "Sprzedane"),
                    ("rezerwacja", "Rezerwacja"),
                ],
                default="dostepne",
                max_length=20,
            ),
        ),
    ]
