# Generated by Django 5.2.5 on 2025-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0002_alter_oferta_inwestycja"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwestycja",
            name="zdjecie",
            field=models.ImageField(blank=True, null=True, upload_to="inwestycje/"),
        ),
    ]
