# Generated by Django 5.2.5 on 2025-09-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "oferty",
            "0002_remove_oferta_inwestycja_remove_oferta_ostatnia_cena_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Inwestycja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200)),
                ("adres", models.CharField(max_length=300)),
                ("data_dodania", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
