# Generated by Django 5.2.5 on 2025-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0002_alter_cena_options_oferta_data_dodania_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cena",
            name="kwota",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="metraz",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
