# Generated by Django 5.2.5 on 2025-08-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0003_alter_cena_kwota_alter_oferta_metraz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oferta",
            name="metraz",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("dostępne", "Dostępne"),
                    ("sprzedane", "Sprzedane"),
                    ("rezerwacja", "Rezerwacja"),
                ],
                default="dostępne",
                max_length=20,
            ),
        ),
    ]
