# Generated by Django 5.2.5 on 2025-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0003_inwestycja_zdjecie"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwestycja",
            name="opis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
