# Generated by Django 5.2.5 on 2025-09-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0004_inwestycja_opis"),
    ]

    operations = [
        migrations.CreateModel(
            name="InwestycjaZdjecie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obraz", models.ImageField(upload_to="inwestycje/galeria/")),
                (
                    "inwestycja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zdjecia",
                        to="oferty.inwestycja",
                    ),
                ),
            ],
        ),
    ]
