# Generated by Django 5.2.5 on 2025-08-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0004_alter_oferta_metraz_alter_oferta_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="oferta",
            name="zdjecie",
            field=models.ImageField(blank=True, null=True, upload_to="oferty/"),
        ),
    ]
