# Generated by Django 5.2.5 on 2025-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0005_oferta_zdjecie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oferta",
            name="zdjecie",
            field=models.ImageField(blank=True, null=True, upload_to="inwestycje/"),
        ),
    ]
