# Generated by Django 5.2.5 on 2025-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0005_inwestycjazdjecie"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwestycja",
            name="standard",
            field=models.TextField(blank=True, null=True),
        ),
    ]
