# Generated by Django 5.2.5 on 2025-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0006_inwestycja_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="oferta",
            name="numer_lokalu",
            field=models.CharField(
                blank=True,
                help_text="Numer lub nazwa lokalu, np. A1/M5",
                max_length=50,
                null=True,
            ),
        ),
    ]
