# Generated by Django 5.2.5 on 2025-08-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0006_alter_oferta_zdjecie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inwestycja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("opis", models.TextField(blank=True, null=True)),
                (
                    "zdjecie",
                    models.ImageField(blank=True, null=True, upload_to="inwestycje/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="oferta",
            name="data_dodania",
        ),
        migrations.AddField(
            model_name="oferta",
            name="opis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="pokoje",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("dostepne", "Dostępne"),
                    ("rezerwacja", "Rezerwacja"),
                    ("sprzedane", "Sprzedane"),
                ],
                max_length=50,
            ),
        ),
    ]
