# Generated by Django 5.2.5 on 2025-08-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0007_inwestycja_remove_oferta_data_dodania_oferta_opis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inwestycja",
            name="nazwa",
            field=models.CharField(max_length=200),
        ),
    ]
