# Generated by Django 5.2.5 on 2025-09-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0007_oferta_numer_lokalu"),
    ]

    operations = [
        migrations.CreateModel(
            name="RodzajLokalu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Rodzaj Lokalu"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="inwestycjazdjecie",
            options={"verbose_name_plural": "Rodzaje Lokali"},
        ),
        migrations.AddField(
            model_name="inwestycja",
            name="numer_pozwolenia",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Numer pozwolenia na budowę",
            ),
        ),
        migrations.AddField(
            model_name="inwestycja",
            name="termin_rozpoczecia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Termin rozpoczęcia inwestycji"
            ),
        ),
        migrations.AddField(
            model_name="inwestycja",
            name="termin_zakonczenia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Termin zakończenia inwestycji"
            ),
        ),
        migrations.AddField(
            model_name="inwestycja",
            name="unikalny_identyfikator_przedsiewziecia",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Unikalny identyfikator przedsięwzięcia",
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="numer_oferty",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Numer Oferty",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="numer_lokalu",
            field=models.CharField(
                blank=True, help_text="Numer lub nazwa lokalu", max_length=50, null=True
            ),
        ),
        migrations.CreateModel(
            name="PomieszczeniePrzynalezne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(
                        max_length=200, verbose_name="Nazwa Pomieszczenia"
                    ),
                ),
                (
                    "powierzchnia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Powierzchnia (m²)",
                    ),
                ),
                (
                    "cena",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cena",
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pomieszczenia_przynalezne",
                        to="oferty.oferta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rabat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(
                        max_length=200, verbose_name="Nazwa Rabatu/Promocji"
                    ),
                ),
                (
                    "wartosc",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Wartość (PLN)"
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[("procentowy", "Procentowy"), ("kwotowy", "Kwotowy")],
                        max_length=50,
                        verbose_name="Typ",
                    ),
                ),
                ("data_od", models.DateField(verbose_name="Data rozpoczęcia")),
                ("data_do", models.DateField(verbose_name="Data zakończenia")),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rabaty",
                        to="oferty.oferta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="oferta",
            name="rodzaj_lokalu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="oferty.rodzajlokalu",
                verbose_name="Rodzaj Lokalu",
            ),
        ),
        migrations.CreateModel(
            name="SwiadczeniePieniezne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=200, verbose_name="Nazwa Świadczenia"),
                ),
                (
                    "kwota",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Kwota"
                    ),
                ),
                ("opis", models.TextField(blank=True, null=True, verbose_name="Opis")),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inne_swiadczenia",
                        to="oferty.oferta",
                    ),
                ),
            ],
        ),
    ]
