# Generated by Django 5.2.5 on 2025-09-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0008_rodzajlokalu_alter_inwestycjazdjecie_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inwestycjazdjecie",
            options={},
        ),
        migrations.AlterModelOptions(
            name="rodzajlokalu",
            options={"verbose_name_plural": "Rodzaje Lokali"},
        ),
        migrations.AlterField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("dostępne", "Dostępne"),
                    ("sprzedane", "Sprzedane"),
                    ("rezerwacja", "Rezerwacja"),
                    ("w_budowie", "W budowie"),
                ],
                default="dostępne",
                max_length=20,
            ),
        ),
    ]
