# Generated by Django 5.2.5 on 2025-08-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0008_alter_inwestycja_nazwa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inwestycja",
            name="nazwa",
            field=models.CharField(max_length=255),
        ),
    ]
